version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    groups:
      minor-updates:
        update-types: [minor]
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: ci
      include: scope
