name: Lint

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      -
        name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          only-new-issues: false
          skip-pkg-cache: true
          skip-build-cache: false
          args: --timeout=10m
